[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "netbox-device-view"
version = "0.2.0"
description = "NetBox Device View plugin"
readme = "README.md"
authors = [{ name = "Peter Baumert" }]
license = {text = "MIT"}
requires-python = ">=3.12"
keywords = ["netbox", "netbox-plugin"]
classifiers = [
    "Framework :: Django",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]

[project.urls]
Homepage = "https://github.com/peterbaumert/netbox-device-view"

[tool.setuptools.packages.find]
where = ["."]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "netbox.settings"
pythonpath = ["/opt/netbox/netbox", "."]
