version: 1

meta:
  description: "Cisco Firepower FPR1120-NGFW-K9"
  background: "#d9d9d9"

canvas:
  columns: 14
  rows: 2

views:
  front:
    rows:
      - blank: 5
      # 8 x copper data ports (Ethernet1/1-8), staggered odd/even
      - sequence:
          kind: interface
          prefix: "ethernet-"
          start: 1
          count: 8
          pattern: top-odd
      - spacer: 1
      # 4 x SFP data ports (Ethernet1/9-12), staggered odd/even
      - sequence:
          kind: interface
          prefix: "ethernet-"
          start: 9
          count: 4
          pattern: top-odd
