services:
  netbox: &netbox
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: netbox-device-view-dev
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    env_file: .env
    volumes:
      - ..:/opt/code/netbox-device-view:cached
      - ./extra.py:/etc/netbox/config/extra.py:ro
    ports:
      - "8000:8080"
    healthcheck:
      test: curl -f http://localhost:8080/login/ || exit 1
      start_period: 90s
      timeout: 3s
      interval: 15s

  netbox-worker:
    <<: *netbox
    depends_on:
      netbox:
        condition: service_healthy
    ports: []
    healthcheck:
      test: ps -aux | grep -v grep | grep -q rqworker || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
    command:
      - /opt/netbox/venv/bin/python
      - /opt/netbox/netbox/manage.py
      - rqworker

  postgres:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - netbox-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -t 2 -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      start_period: 20s
      timeout: 3s
      interval: 15s

  redis:
    image: valkey/valkey:9-alpine
    command: valkey-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - netbox-redis-data:/data
    healthcheck:
      test: "[ $$(valkey-cli --pass \"${REDIS_PASSWORD}\" ping) = 'PONG' ]"
      start_period: 5s
      timeout: 3s
      interval: 5s

  redis-cache:
    image: valkey/valkey:9-alpine
    command: valkey-server --requirepass ${REDIS_CACHE_PASSWORD}
    healthcheck:
      test: "[ $$(valkey-cli --pass \"${REDIS_CACHE_PASSWORD}\" ping) = 'PONG' ]"
      start_period: 5s
      timeout: 3s
      interval: 5s

volumes:
  netbox-postgres-data:
  netbox-redis-data:
