# Generated by Django 5.2.11 on 2026-03-13 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0226_modulebay_rebuild_tree"),
        ("netbox_device_view", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceview",
            name="device_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="dcim.devicetype",
            ),
        ),
    ]
